
### ~/config.yaml
defaults:
  - parameters: parameters
  - _self_

local: /Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/
pathTrainingDataset: basin1TrainUnbalanced.csv

targetColName: percentage

# @package _group_
name: param
dataPath : 
dataLoaderArgs :  {'batch_size': 1, 'num_workers': 4,'drop_last': True}
model: UNetFlood
modelMode: train
loss: lovasz_hinge
optimizer: Adam
OptimizerParams : {'lr': 0.0001}
scheduler: plateau
hydra: default
override hydra/hydra_logging: colorlog # enable color logging to make it pretty
override hydra/job_logging: colorlog # enable color logging to make it pretty