## ~/config/OPS/configPC.ymal

defaults:
  - parameters: configTraining
  - _self_

work_dir: ${hydra:runtime.cwd}  # where the code is executed
config_name: ${hydra:job.config_name}
config_override_dirname: ${hydra:job.override_dirname}
config_path: ${hydra:runtime.config_sources}
projectRoot: C:\Users\abfernan\CrossCanFloodMapping\DL4Flood
saveModelsPath: ${projectRoot}\savedModels\

dataRoot: C:\Users\abfernan\CrossCanFloodMapping\DatasetCNNFlood\C1Dataset\Percentage_1
rawDataList: C:\Users\abfernan\CrossCanFloodMapping\DatasetCNNFlood\C1Dataset\Percentage_1\TrainingDataSource_Percentage_1_feat1_min-annot1_trn.csv
trainingDataList : ${dataRoot}\SplitedTrainingSetPlusRotated.csv
validationDataList: ${dataRoot}\SplitedValSet.csv
testingDataList: ${dataRoot}\Percentage_1_testSet\Percentage_1_testSet_feat1_min-annot1_trn.csv
permanentTransformetionSavePath : ${dataRoot}\trn
standardizerSavePath : ${dataRoot}\standardizers.csv
