## ~/config/OPS/configVelum.ymal

defaults:
  - parameters: trainingParamsVelum
  - _self_

work_dir: ${hydra:runtime.cwd}  
config_name: ${hydra:job.config_name}
config_override_dirname: ${hydra:job.override_dirname}
config_path: ${hydra:runtime.config_sources}
projectRoot: /home/abfernan/CrossCanFloodMap/DL4Flood/
saveModelsPath: ${hydra:runtime.cwd} 

dataRoot:  /home/abfernan/CrossCanFloodMap/DatasetCNNFlood/C1Dataset 
rawDataList: ${dataRoot}/Percentage_1/Percentage_1_feat1_min-annot1_trn.csv
trainingDataList : ${dataRoot}/Percentage_1_IntensiveSampl/SplitedTrainingSet_C1IntensiveSampl.csv
validationDataList: ${dataRoot}/Percentage_1_IntensiveSampl/SplitedValSet_C1IntensivSampl.csv
testingDataList: ${dataRoot}/Percentage_1_tst/Percentage_1_tst_feat1_min-annot1_tst.csv
permanentTransformetionSavePath : ${dataRoot}/Percentage_1/trn/
standardizerSavePath : ${dataRoot}/standardizers.csv
