
### ~\config\parameters\configTraining.yaml
targetColName: percentage
epochs : 50
dataLoaderArgs :  {'batch_size': 1, 'num_workers': 4,'drop_last': True}
scheduler: plateau
makeTest: True
hydra: default
override hydra/hydra_logging: colorlog # enable color logging to make it pretty
override hydra/job_logging: colorlog # enable color logging to make it pretty
modelMode: train
# @package _global_
model:
  _target_: model_set.models.UNetFlood
  classes : 1
  in_channels : 1
  dropout: False    # (bool) Use dropout or not
  prob: 0.   # float: 0. - 0.99
loss_fn:
  _partial_: True 
  _target_: scr.losses.lovasz_hinge
metric_fn :
  _partial_: True 
  _target_: scr.losses.iou_binary 
optimizer:
  _target_: torch.optim.Adam
  maximize : True
  lr: 0.000005
  weight_decay : 0.9