
### ~\config\parameters\configTraining.yaml
targetColName: percentage
epochs : 1 
dataLoaderArgs :  {'batch_size': 1, 'num_workers': 4,'drop_last': True}
optimizer: Adam
optimizerParams : {'lr': 0.001}
scheduler: plateau
makeTest: True
hydra: default
override hydra/hydra_logging: colorlog # enable color logging to make it pretty
override hydra/job_logging: colorlog # enable color logging to make it pretty
modelMode: train
# @package _global_
model:
  _target_: models.unet.UNetFlood
  dropout: True    # (bool) Use dropout or not
  prob: True
loss_fn: 
  _target_: scr.losses.lovasz_hinge
metric_fn :
  _target_: scr.losses.lovasz_hinge 